### PR TITLE
Enable CPU share param

### PR DESCRIPTION
**Pull request by swat30**
Issue #8

### CODE REVIEW

**Comment by swat30** [comment]
@thurloat plz review when you have a sec

**Comment by thurloat** [comment]
how do you use?

**Comment by swat30** [comment]
`/docrane/container/cpu_shares 1024`

**Comment by thurloat** [comment]
does 1024 mean unlimited cpus?

maybe i should RTFM

**Comment by swat30** [comment]
yea, RTFM MFer ;)

**Comment by thurloat** [comment]
RTFM'd LGTM

**Pull request merged**
